create table assistant_conversations (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create index idx_assistant_conversations_group_id on assistant_conversations(group_id);

create table assistant_messages (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    sequence_number integer not null,
    role varchar(20) not null,
    content text not null,
    tool_name varchar(255),
    created_at timestamp not null default current_timestamp,
    constraint fk_assistant_message_to_conversation foreign key (conversation_id) references assistant_conversations (id) on delete cascade,
    constraint uk_assistant_message_conversation_sequence unique (conversation_id, sequence_number)
);

create index idx_assistant_messages_conversation_id on assistant_messages(conversation_id);