CREATE TABLE document_chunks (
    id bigint generated by default as identity primary key,
    group_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    chunk_number INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    metadata_json jsonb,
    start_position INTEGER,
    end_position INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_chunk_to_document FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE
);

CREATE INDEX idx_document_chunk_group_id ON document_chunks (group_id);
CREATE INDEX idx_document_chunk_document_id ON document_chunks (document_id);
CREATE INDEX idx_document_chunk_group_document ON document_chunks (group_id, document_id, chunk_number);