create table if not exists users (
                                      id bigint generated by default as identity primary key,
                                      group_id bigint not null,
                                      username varchar(100) not null,
                                      email varchar(255) not null,
                                      password_hash varchar(255) not null,
                                      first_name varchar(100) not null,
                                      last_name varchar(100) not null,
                                      enabled boolean not null default true,
                                      created_at timestamp not null default current_timestamp,
                                      updated_at timestamp not null default current_timestamp,
                                      constraint uk_users_username unique (username),
                                      constraint uk_users_email unique (email)
);

create index idx_users_group on users(group_id);
create index idx_users_username_group on users(username, group_id);

insert into users (group_id, username, email, password_hash, first_name, last_name, enabled)
values
    (1, 'jsmith', 'jane.smith@example.com', '$2a$10$N9qo8uLOickgx2ZMRZoMy.Mrq4X1G3z8ChjyaW.0h6t1WvT8xRj9m', 'Jane', 'Smith', true),
    (1, 'rkumar', 'raj.kumar@example.com', '$2a$10$7EqJtq98hPqEX7fNZaFWoOe6DAo3vXV5NpjJfW7uJlD5c1nY0X2Aa', 'Raj', 'Kumar', true),
    (1, 'mgarcia', 'maria.garcia@example.com', '$2a$10$UwYzZBQK9v3g0k8xNCfhVe.i9zwq7WgN1lRt5oZbYw2CzKz0dJXeS', 'Maria', 'Garcia', false);
