create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(255) not null,
    expires_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_refresh_tokens_user unique (user_id),
    constraint fk_refresh_tokens_user foreign key (user_id) references users(id)
);
