create table if not exists claims (
                                       id bigint generated by default as identity primary key,
                                       user_id bigint not null references users(id),
                                       group_id bigint not null,
                                       policy_id varchar(50) not null,
                                       claim_reference varchar(20) not null,
                                       claim_status varchar(20) not null default 'PENDING',
                                       claim_amount decimal(12,2),
                                       service_date date not null,
                                       filing_date timestamp default current_timestamp,
                                       provider_name varchar(200),
                                       diagnosis_code varchar(20),
                                       created_at timestamp not null default current_timestamp,
                                       updated_at timestamp not null default current_timestamp,
                                       constraint uk_claims_claim_reference unique (claim_reference)
);

create index idx_claims_user_group_service on claims(user_id, group_id, service_date desc);
create index idx_claims_group on claims(group_id);

insert into claims (user_id, group_id, policy_id, claim_reference, claim_status, claim_amount, service_date, provider_name, diagnosis_code)
values
    (1, 1, 'POL-100234', 'CLM-2026-000001', 'PAID',      245.00, date '2026-02-14', 'Riverside Family Clinic', 'J06.9'),
    (1, 1, 'POL-100234', 'CLM-2026-000002', 'APPROVED',  680.50, date '2026-03-22', 'Northgate Imaging Center', 'M54.5'),
    (1, 1, 'POL-100234', 'CLM-2026-000003', 'DENIED',    120.00, date '2026-04-30', 'Riverside Family Clinic', 'E11.9'),
    (1, 1, 'POL-100234', 'CLM-2026-000004', 'IN_REVIEW', 950.75, date '2026-06-10', 'Lakeside Physical Therapy', 'M25.561'),
    (1, 1, 'POL-100234', 'CLM-2026-000005', 'PENDING',   310.20, date '2026-07-25', 'Northgate Imaging Center', 'R51'),

    (2, 1, 'POL-100587', 'CLM-2026-000006', 'PAID',      175.00, date '2026-02-28', 'Cedar Valley Dental', 'K02.9'),
    (2, 1, 'POL-100587', 'CLM-2026-000007', 'APPROVED',  420.00, date '2026-04-05', 'Cedar Valley Dental', 'K05.10'),
    (2, 1, 'POL-100587', 'CLM-2026-000008', 'PENDING',   865.30, date '2026-05-17', 'Metro General Hospital', 'S93.401A'),
    (2, 1, 'POL-100587', 'CLM-2026-000009', 'DENIED',     95.00, date '2026-06-21', 'Cedar Valley Dental', 'K08.1'),
    (2, 1, 'POL-100587', 'CLM-2026-000010', 'IN_REVIEW', 530.60, date '2026-08-01', 'Metro General Hospital', 'M79.601'),

    (3, 1, 'POL-100912', 'CLM-2026-000011', 'PAID',      290.00, date '2026-02-09', 'Sunrise Urgent Care', 'J45.909'),
    (3, 1, 'POL-100912', 'CLM-2026-000012', 'PENDING',   150.00, date '2026-03-15', 'Sunrise Urgent Care', 'R05'),
    (3, 1, 'POL-100912', 'CLM-2026-000013', 'APPROVED', 1200.00, date '2026-05-02', 'Metro General Hospital', 'S52.501A'),
    (3, 1, 'POL-100912', 'CLM-2026-000014', 'IN_REVIEW', 410.90, date '2026-06-30', 'Lakeside Physical Therapy', 'M17.11'),
    (3, 1, 'POL-100912', 'CLM-2026-000015', 'DENIED',     75.00, date '2026-07-19', 'Sunrise Urgent Care', 'J02.9');