create table documents (
                           id bigint generated by default as identity primary key,
                           group_id bigint not null,
                           uploader_user_id bigint not null,
                           file_name varchar(255) not null,
                           file_ext varchar(16) not null,
                           content_type varchar(128),
                           file_size bigint not null,
                           file_hash VARCHAR(128),
                           storage_bucket varchar(128) not null,
                           storage_object_key varchar(512) not null,
                           status varchar(50) not null default 'PENDING',
                           deleted boolean not null default false,
                           failure_reason text,
                           uploaded_at timestamp,
                           processed_at timestamp,
                           created_at timestamp not null default current_timestamp,
                           updated_at timestamp not null default current_timestamp,
                           constraint uk_documents_storage_object_key unique (storage_object_key)
);

create index idx_documents_group on documents(group_id);
create index idx_documents_group_deleted_status on documents(group_id, deleted, status);
create index idx_documents_uploader_user on documents(uploader_user_id);
create index idx_documents_group_hash_active on documents (group_id, file_hash) where deleted = false and file_hash is not null;






